//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class Audit_Customer
    {
        public int AuditID { get; set; }
        public int CustomerID { get; set; }
        public string OldSurname { get; set; }
        public string NewSurname { get; set; }
        public string OldName { get; set; }
        public string NewName { get; set; }
        public string OldAdress { get; set; }
        public string NewAdress { get; set; }
        public Nullable<int> OldZipCode { get; set; }
        public Nullable<int> NewZipCode { get; set; }
        public string OldCity { get; set; }
        public string NewCity { get; set; }
        public Nullable<int> OldPhoneNo { get; set; }
        public Nullable<int> NewPhoneNo { get; set; }
        public string OldEmail { get; set; }
        public string NewEmail { get; set; }
        public string OldPassword { get; set; }
        public string NewPassword { get; set; }
        public Nullable<decimal> OldTotalAmount { get; set; }
        public Nullable<decimal> NewTotalAmount { get; set; }
        public string HostName { get; set; }
        public int HostID { get; set; }
        public string OperatingSystemUser { get; set; }
        public int OperatingSystemID { get; set; }
        public System.DateTime updated_at { get; set; }
        public string operation { get; set; }
    }
}
