USE [master]
GO

/****** Object:  Database [Product]    Script Date: 12/1/2019 10:05:18 PM ******/
CREATE DATABASE [Product]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Product', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\Product_Primary.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Product_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\Product_Primary.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Product].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Product] SET ANSI_NULL_DEFAULT ON 
GO

ALTER DATABASE [Product] SET ANSI_NULLS ON 
GO

ALTER DATABASE [Product] SET ANSI_PADDING ON 
GO

ALTER DATABASE [Product] SET ANSI_WARNINGS ON 
GO

ALTER DATABASE [Product] SET ARITHABORT ON 
GO

ALTER DATABASE [Product] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Product] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Product] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Product] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Product] SET CURSOR_DEFAULT  LOCAL 
GO

ALTER DATABASE [Product] SET CONCAT_NULL_YIELDS_NULL ON 
GO

ALTER DATABASE [Product] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Product] SET QUOTED_IDENTIFIER ON 
GO

ALTER DATABASE [Product] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Product] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Product] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Product] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Product] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Product] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Product] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Product] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Product] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Product] SET RECOVERY FULL 
GO

ALTER DATABASE [Product] SET  MULTI_USER 
GO

ALTER DATABASE [Product] SET PAGE_VERIFY NONE  
GO

ALTER DATABASE [Product] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Product] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Product] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [Product] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Product] SET QUERY_STORE = OFF
GO

ALTER DATABASE [Product] SET  READ_WRITE 
GO


