CREATE LOGIN [FullAdminUser] WITH PASSWORD=N'App12345', DEFAULT_DATABASE=[Product], CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO
USE [Product]
GO
CREATE USER [FullAdminUser] FOR LOGIN [FullAdminUser]
GO
ALTER USER [FullAdminUser] WITH DEFAULT_SCHEMA=[dbo]
GO
ALTER ROLE [db_owner] ADD MEMBER [FullAdminUser]
GO


CREATE LOGIN [ReadOnlyUser] WITH PASSWORD=N'App12345', DEFAULT_DATABASE=[Product], CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO
USE [Product]
GO
CREATE USER [ReadOnlyUser] FOR LOGIN [ReadOnlyUser]
GO
ALTER USER [ReadOnlyUser] WITH DEFAULT_SCHEMA=[dbo]
GO
ALTER ROLE [db_datareader] ADD MEMBER [ReadOnlyUser]
GO

CREATE LOGIN [RestrictedUser] WITH PASSWORD=N'App12345', DEFAULT_DATABASE=[Product], CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO
USE [Product]
GO
CREATE USER [RestrictedUser] FOR LOGIN [RestrictedUser]
GO
ALTER USER [RestrictedUser] WITH DEFAULT_SCHEMA=[dbo]
GO
ALTER ROLE [db_datareader] ADD MEMBER [RestrictedUser]
GO
DENY INSERT, SELECT , UPDATE ON Invoice TO  [RestrictedUser]
GO
DENY INSERT, SELECT , UPDATE ON InvoiceLine TO  [RestrictedUser]
GO